[package]
name = "sha_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
log.workspace = true
nanoid = "0.4.0"
oxc = "0.108.0"
oxc_codegen = "0.108.0"
tera = "1.20.1"
thiserror = "2.0.17"
walkdir = "2.5.0"
