[package]
name = "sha_validator"
version = "0.1.0"
edition = "2024"
sha_utils = { path = "../sha-utils" }

[dependencies]
log.workspace = true
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.10"
thiserror = "2.0.17"
sha_utils = { version = "0.1.0", path = "../sha-utils" }
